project:
  type: website
  output-dir: docs

website:
  title: "Demographic Change in Munich"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: proposal.qmd
        text: Proposal
      - href: report.qmd
        text: Final Report
      - href: group-reflection.qmd
        text: Group Reflection
    right:
      - icon: github
        href: https://github.com/Echoanno/StatProg_II_group_0.git


format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    number-sections: true
    code-fold: true
    code-tools: true
    fig-align: center
    page-layout: full
execute:
  warning: false
  message: false